<a href="https://colab.research.google.com/github/FaustoFLES/Programacion-Analitica/blob/main/Practica_4_Manipulaci%C3%B3n_de_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Crea la primera matriz de 3x3 con números aleatorios entre 1 y 10
matrix1 = np.random.randint(1, 11, size=(3, 3))

# Crea la segunda matriz de 3x3 con números aleatorios entre 1 y 10
matrix2 = np.random.randint(1, 11, size=(3, 3))

# Muestra las matrices
print("Matriz 1:")
display(matrix1)

print("\nMatriz 2:")
display(matrix2)

# Suma las matrices
sum_matrix = matrix1 + matrix2

# Muestra la matriz resultante de la suma
print("\nSuma de las matrices:")
display(sum_matrix)

# Resta la segunda matriz de la primera
subtract_matrix = matrix1 - matrix2

# Muestra la matriz resultante de la resta
print("\nResta de la segunda matriz de la primera:")
display(subtract_matrix)

# Multiplica la primera matriz por 2
multiply_matrix = matrix1 * 2

# Muestra la matriz resultante de la multiplicación
print("\nMultiplicación de la primera matriz por 2:")
display(multiply_matrix)

# Multiplicación matricial entre las dos matrices
matrix_multiply = matrix1 @ matrix2

# Muestra la matriz resultante de la multiplicación matricial
print("\nMultiplicación matricial de las dos matrices:")
display(matrix_multiply)

Matriz 1:


array([[9, 2, 7],
       [9, 8, 7],
       [4, 8, 4]])


Matriz 2:


array([[ 3,  5,  2],
       [ 4,  9,  9],
       [10,  4,  6]])


Suma de las matrices:


array([[12,  7,  9],
       [13, 17, 16],
       [14, 12, 10]])


Resta de la segunda matriz de la primera:


array([[ 6, -3,  5],
       [ 5, -1, -2],
       [-6,  4, -2]])


Multiplicación de la primera matriz por 2:


array([[18,  4, 14],
       [18, 16, 14],
       [ 8, 16,  8]])


Multiplicación matricial de las dos matrices:


array([[105,  91,  78],
       [129, 145, 132],
       [ 84, 108, 104]])